# Generated by Django 4.2.5 on 2024-03-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=20)),
                ('Blood_Type', models.CharField(choices=[('O-', 'O-ve'), ('O+', 'O+ve'), ('B-', 'B-ve'), ('B+', 'B+ve'), ('AB+', 'AB+ve'), ('AB-', 'AB-ve'), ('A+', 'A+ve'), ('A-', 'A-ve')], max_length=20)),
                ('Medical_Condition', models.CharField(max_length=20)),
                ('Date_of_Admission', models.DateField()),
                ('Doctor', models.CharField(max_length=20)),
                ('Insurance_Provider', models.CharField(max_length=20)),
                ('Billing_Amount', models.FloatField()),
                ('Room_Number', models.IntegerField()),
                ('Admission_Type', models.CharField(choices=[('Elective', 'Elective'), ('Emergency', 'Emergency'), ('Urgent', 'Urgent')], max_length=20)),
                ('Discharge_Date', models.DateField()),
                ('Medication', models.CharField(max_length=20)),
                ('Test_Result', models.CharField(choices=[('Abnormal', 'Abnormal'), ('Inconclusive', 'Inconclusive'), ('Normal', 'Normal')], max_length=20)),
            ],
        ),
    ]
