/* Source and licensing information for the line(s) below can be found at https://www.himss.org/sites/all/themes/base_theme/js/css-vars-ponyfill.js. */
;cssVars({});
/* Source and licensing information for the above line(s) can be found at https://www.himss.org/sites/all/themes/base_theme/js/css-vars-ponyfill.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.himss.org/sites/all/themes/base_theme/js/append-polyfill.js. */
(function(e){e.forEach(function(e){if(e.hasOwnProperty('append')){return};Object.defineProperty(e,'append',{configurable:!0,enumerable:!0,writable:!0,value:function(){const argArr=Array.prototype.slice.call(arguments);const docFrag=document.createDocumentFragment();argArr.forEach(function(e){const isNode=e instanceof Node;docFrag.appendChild(isNode?e:document.createTextNode(String(e)))});this.appendChild(docFrag)}})})})([Element.prototype,Document.prototype,DocumentFragment.prototype]);
/* Source and licensing information for the above line(s) can be found at https://www.himss.org/sites/all/themes/base_theme/js/append-polyfill.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.himss.org/sites/hde/modules/custom/administration/assets/js/eu_cookie_compliance_settings_button.js. */
(function(o,e){e.behaviors.euCookieComplianceSettingsButton={attach:function(){o('.eu-cookie-compliance-settings-button').click(function(t){t.preventDefault();e.eu_cookie_compliance.toggleWithdrawBanner();o('#sliding-popup').remove();e.eu_cookie_compliance.setStatus(null);e.eu_cookie_compliance.execute();return!1})}}})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.himss.org/sites/hde/modules/custom/administration/assets/js/eu_cookie_compliance_settings_button.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.himss.org/core/assets/vendor/js-cookie/js.cookie.min.js. */
/*! js-cookie v3.0.0-rc.0 | MIT */
!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?module.exports=t():"function"==typeof define&&define.amd?define(t):(e=e||self,function(){var r=e.Cookies,n=e.Cookies=t();n.noConflict=function(){return e.Cookies=r,n}}())}(this,function(){"use strict";function e(e){for(var t=1;t<arguments.length;t++){var r=arguments[t];for(var n in r)e[n]=r[n]}return e}var t={read:function(e){return e.replace(/%3B/g,";")},write:function(e){return e.replace(/;/g,"%3B")}};return function r(n,i){function o(r,o,u){if("undefined"!=typeof document){"number"==typeof(u=e({},i,u)).expires&&(u.expires=new Date(Date.now()+864e5*u.expires)),u.expires&&(u.expires=u.expires.toUTCString()),r=t.write(r).replace(/=/g,"%3D"),o=n.write(String(o),r);var c="";for(var f in u)u[f]&&(c+="; "+f,!0!==u[f]&&(c+="="+u[f].split(";")[0]));return document.cookie=r+"="+o+c}}return Object.create({set:o,get:function(e){if("undefined"!=typeof document&&(!arguments.length||e)){for(var r=document.cookie?document.cookie.split("; "):[],i={},o=0;o<r.length;o++){var u=r[o].split("="),c=u.slice(1).join("="),f=t.read(u[0]).replace(/%3D/g,"=");if(i[f]=n.read(c,f),e===f)break}return e?i[e]:i}},remove:function(t,r){o(t,"",e({},r,{expires:-1}))},withAttributes:function(t){return r(this.converter,e({},this.attributes,t))},withConverter:function(t){return r(e({},this.converter,t),this.attributes)}},{attributes:{value:Object.freeze(i)},converter:{value:Object.freeze(n)}})}(t,{path:"/"})});

/* Source and licensing information for the above line(s) can be found at https://www.himss.org/core/assets/vendor/js-cookie/js.cookie.min.js. */;
